name: Sasa's weeks cd

on:
    workflow_dispatch:
    push:
        branches:
            - main

jobs:
    frontend-ci:
        name: Frontend Build
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: app/client
        steps:
        - name: Checkout repo
          uses: actions/checkout@v3

        - name: Set up Node.js for frontend
          uses: actions/setup-node@v3
          with:
            node-version: 18

        - name: Install frontend dependencies
          run: npm install

        - name: Build frontend
          run: npm run build

        - name: Upload build artifact
          uses: actions/upload-artifact@v3
          with:
            name: frontend-build
            path: dist

    frontend-deploy:
        name: Deploy Frontend to GitHub Pages
        needs: frontend-ci
        runs-on: ubuntu-latest
        if: success()
        steps:
        - name: Download frontend build artifact
          uses: actions/download-artifact@v4
          with:
            name: frontend-build
            path: ./client/dist

        - name: Deploy to GitHub Pages
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./dist